Repository ureca-itPlace/itplace-front, pull requests merged in 2025-07, with the labels that each got.

#12 Feat/랜딩 페이지 CTA 섹션 구현
  public/images/landing/CTARabbit.svg
  src/features/landingPage/StartCTASection.tsx
  src/features/landingPage/components/Button.tsx
  src/features/landingPage/components/components/Button.tsx
  src/pages/LandingPage.tsx
Labels: ✨ Feature

#40 마이페이지 찜한 혜택 탭 기능 구현 완료
  public/images/bunny-no-result.png
  public/images/bunny-no-result.webp
  public/images/mock/cgv.png
  public/images/mock/gs25.png
  public/images/mock/turucar.png
  public/images/myPage/bunny-favorites.png
  public/images/myPage/bunny-favorites.webp
  public/images/myPage/bunny-history.png
  public/images/myPage/bunny-history.webp
  public/images/myPage/bunny-info.png
  public/images/myPage/bunny-info.webp
  public/images/myPage/icon-check.png
  public/images/myPage/icon-file.png
  public/images/myPage/icon-file.webp
  public/images/myPage/icon-money.webp
  public/images/myPage/icon-nothing.webp
  src/components/Header.tsx
  src/components/common/BenefitFilterToggle.tsx
  src/components/common/README.md
  src/features/myPage/.gitkeep
  src/features/myPage/components/BenefitDetailTabs.tsx
  src/features/myPage/components/FadeWrapper.tsx
  src/features/myPage/components/MainContentWrapper.tsx
  src/features/myPage/components/RightAside.tsx
  src/features/myPage/components/SideMenu.tsx
  src/features/myPage/mock/mockData.ts
  src/layouts/MyPageLayout.tsx
  src/pages/myPage/MyFavoritesPage.tsx
  src/pages/myPage/MyHistoryPage.tsx
  src/pages/myPage/MyInfoPage.tsx
  src/pages/myPage/MyPage.tsx
  src/routes/index.tsx
Labels: 🎨 Design, ✨ Feature

#42 style : 관리자 페이지 스타일 수정 및
  src/components/common/ActionButton.tsx
  src/components/common/AdminModal.tsx
  src/components/common/DataTable.tsx
  src/components/common/FilterDropdown.tsx
  src/components/common/Pagination.tsx
  src/components/common/RankingList.tsx
  src/components/common/StatisticsCard.tsx
  src/features/adminPage/components/Dashboard/ClickStatistics.tsx
  src/features/adminPage/components/Dashboard/UsageStatistics.tsx
  src/features/adminPage/components/Dashboard/WishlistChart.tsx
  src/features/adminPage/components/Dashboard/index.tsx
  src/features/adminPage/components/MemberManagement/MemberDetailModal.tsx
  src/features/adminPage/components/PartnershipManagement/PartnerDetailModal.tsx
  src/features/adminPage/components/PartnershipManagement/index.tsx
  src/features/adminPage/components/Sidebar/index.tsx
Labels: 🛠️ Refactor, 🎨 Design

#54 별버튼 찜 취소 로직 모달 뜨도록 수정
  src/features/myPage/components/SideMenu.tsx
  src/pages/myPage/MyFavoritesPage.tsx
Labels: 🎨 Design, ✨ Feature

#191 ScrollToTop 기능 구현 및 전역에 적용 & 바텀시트 dvh적용
  src/components/AllBenefitsModal.tsx
  src/components/ScrollToTop.tsx
  src/features/allBenefitsPage/index.tsx
  src/features/mainPage/components/Layout/index.tsx
  src/layouts/MyPageLayout.tsx
  src/layouts/ResponsiveLayout.tsx
  src/pages/ScrollToTopHandler.tsx
  src/pages/myPage/MyFavoritesPage.tsx
  src/routes/index.tsx
Labels: ✨ Feature

#196 바텀시트 UX 어색한 부분 해결 및 noresult 이미지 개선
  public/images/bunny-login-require.png
  public/images/bunny-login-require.webp
  public/images/bunny-no-result.png
  public/images/bunny-no-result.webp
  src/features/allBenefitsPage/index.tsx
  src/features/loginPage/components/login/KakaoLoginButton.tsx
  src/features/loginPage/components/login/LoginForm.tsx
  src/features/loginPage/layouts/AuthLayout.tsx
  src/features/mainPage/components/Layout/index.tsx
Labels: 🛠️ Refactor

#206 feat: NotFound 페이지 구현
  public/images/notfound/notfound-bg-mobile.webp
  public/images/notfound/notfound-bg.webp
  src/pages/NotFoundPage.tsx
Labels: ✨ Feature
