Repository ureca-itPlace/itplace-front, pull requests merged in 2025-08, with the labels that each got.

#216 메인페이지 잇플AI 채팅방 구현
  src/features/mainPage/components/Layout/index.tsx
  src/features/mainPage/components/SidebarSection/AllBenefit/index.tsx
  src/features/mainPage/components/SidebarSection/RecommendStoreList/ChatRoom/ChatRoom.tsx
  src/features/mainPage/components/SidebarSection/RecommendStoreList/index.tsx
  src/features/mainPage/components/SidebarSection/index.tsx
Labels: 🎨 Design, ✨ Feature

#232 fix: 마이페이지 타임존 문제 해결
  src/pages/myPage/MyHistoryPage.tsx
Labels: 👾 Bug

#239 Fix/랜딩 페이지 애니메이션 반응형 즉시 적용이 되지 않는 문제 해결 및 성능 최적화
  index.html
  package-lock.json
  package.json
  public/images/landing/hero/hero-bg-mobile.webp
  public/images/landing/hero/hero-bg.webp
  public/images/landing/hero/spaceship-window.webp
  src/components/MobileHeader.tsx
  src/features/landingPage/components/FeatureItem.tsx
  src/features/landingPage/components/Video.tsx
  src/features/landingPage/sections/FeatureSection.tsx
  src/features/landingPage/sections/HeroSection.tsx
  src/features/landingPage/sections/VideoSection.tsx
  src/pages/LandingPage.tsx
Labels: 👾 Bug, 🛠️ Refactor

#250 Fix/240 front debug sejin
  public/images/main/tab-highlight.webp
  src/components/ToastProvider.tsx
  src/features/allBenefitsPage/index.tsx
  src/features/eventPage/components/Modal/StarModal.tsx
  src/features/landingPage/sections/HeroSection.tsx
  src/features/mainPage/components/SidebarSection/NavigationTabsSection/index.tsx
  src/features/mainPage/components/SidebarSection/StoreDetail/StoreDetailActionButton.tsx
  src/hooks/useHeaderThemeObserver.ts
  src/hooks/useIsMobile.ts
  src/index.css
  src/utils/Animation.ts
  src/utils/toast.tsx
Labels: 🛠️ Refactor

#264 마이페이지 사소한 버그 수정
  src/features/myPage/components/Favorites/BenefitDetailTabs.tsx
Labels: 👾 Bug

#266 Update README.md
  README.md
  demo/event.gif
Labels: 📑 Docs

#267 Update README.md
  README.md
Labels: 📑 Docs
